# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Ed Pollitt
tagline:          ''
description:      ''
url:              https://edpollitt.github.io
baseurl:          /

author:
  name:           'Ed Pollitt'
  url:            https://github.com/edpollitt/

timezone: <timezone>
exclude: ['Gemfile', 'Gemfile.lock', '*.sublime-*', 'lib','vendor', 'Rakefile', 'about.md']

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/edpollitt/
